import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className="light"
      style={
        {
          colorScheme: "light",
          viewTransitionName: "root",
        } as React.CSSProperties
      }
    >
      <head>
        <meta name="view-transition" content="same-origin" />
      </head>
      <body
        className={`${inter.variable} font-sans bg-white text-gray-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
